name: Multi-Job Workflow

on: 
  push
  
jobs:
  buildnpm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          echo "npm build"
          ipaddr a
          hostname"
          echo "Building the npm project..."
          # Add your build commands here

  testnpm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Running tests..."
          ipaddr a
          hostname
          # Add your test commands here
