name: If Condition and Script Block Example

on:
  workflow_dispatch

jobs:
  example_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Display branch name
        run: echo "Current branch: ${{ github.ref }}"
        
      - name: Conditional step
        if: github.ref == 'refs/heads/main'
        run: echo "This step runs only on the 'main' branch"
        
      - name: Script block example
        run: |
          echo "This is a script block example"
          echo "Performing some tasks..."
          echo "Script block completed"
