name: Workflow Dispatch Example

on:
  workflow_dispatch:
    inputs:
      bucketname:
        description: 'An example string variable'
        required: false
        default: ''
      bucketregion:
        description: 'An example string variable'
        required: true
        default: 'Hello, World!'
      lists:
        description: 'An example list variable (comma-separated)'
        required: true
        default: 'item1,item2,item3,item4'

jobs:
  example_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Display inputs
        run: |
          echo "creating bucket name with this: ${{ github.event.inputs.bucketname }} in the region  ${{ github.event.inputs.bucketregion }}"
          
          IFS=',' read -ra LIST_ITEMS <<< "${{ github.event.inputs.lists }}"
          echo "Example List:"
          for item in "${LIST_ITEMS[@]}"; do
            echo "- $item"
          done
