name: Python Shell Example

on:
  push:
    branches:
      - main

jobs:
  example_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run Python shell command
        run: |
          python -c "print('Hello from Python shell')"
